apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: scheduling-demo
spec:
  selector:
    app: catalog

  ports:
    - port: 80
      targetPort: 8080

  type: ClusterIP

  trafficDistribution: PreferClose